--CREACION DE STORED PROCEDURES
USE Com5600G04;
GO

--REGISTRAR SUCURSALES
CREATE OR ALTER PROCEDURE SUCURSAL.REGISTRAR_SUCURSAL(@CIUDAD VARCHAR(20), 
@DIRECCION VARCHAR(70), @HORARIO VARCHAR(30), @TELEFONO CHAR(15)) AS
BEGIN
	INSERT INTO SUCURSAL.SUCURSAL(ciudad, direccion, horario, telefono) 
	VALUES (@CIUDAD, @DIRECCION, @HORARIO, @TELEFONO)
END
GO

--BAJA DE SUCURSALES
CREATE OR ALTER PROCEDURE SUCURSAL.BAJAR_SUCURSAL(@ID INT) AS 
BEGIN
	UPDATE SUCURSAL.sucursal SET BAJA = getdate WHERE ID = @ID
END
GO

--ALTA SUCURSALES
CREATE OR ALTER PROCEDURE SUCURSAL.ALTA_SUCURSAL(@ID INT) AS 
BEGIN
	UPDATE SUCURSAL.SUCURSAL SET BAJA = NULL WHERE ID = @ID
END
GO

--REGISTRAR EMPLEADOS
CREATE OR ALTER PROCEDURE SUCURSAL.REGISTRAR_EMPLEADO(@NOMBRE VARCHAR(20), 
@APELLIDO VARCHAR(20),@DNI CHAR(9), @DIRECCION VARCHAR(100), @MAILPERSONAL VARCHAR(50), 
@MAILEMPRESARIAL VARCHAR(50), @CUIL CHAR(12), @CARGO VARCHAR(20), @SUCURSAL VARCHAR(20), 
@TURNO VARCHAR(20)) AS
BEGIN
	INSERT INTO SUCURSAL.empleado(nombre, apellido, dni, direccion, 
	email_personal, email_empresarial, cuil, cargo,  sucursal, turno) 
	VALUES (@NOMBRE, @APELLIDO, @DNI, @DIRECCION, @MAILPERSONAL, @MAILEMPRESARIAL, 
	@CUIL, @CARGO, @SUCURSAL, @TURNO);
END
GO

--BAJA DE EMPLEADOS
CREATE OR ALTER PROCEDURE SUCURSAL.BAJAR_EMPLEADO(@LEGAJO INT) AS 
BEGIN
	UPDATE SUCURSAL.EMPLEADO SET BAJA = getdate() WHERE legajoId = @LEGAJO
END
GO

--ALTA EMPLEADOS
CREATE OR ALTER PROCEDURE SUCURSAL.ALTA_EMPLEADO(@LEGAJO INT) AS 
BEGIN
	UPDATE SUCURSAL.EMPLEADO SET BAJA = NULL WHERE LEGAJOID = @LEGAJO
END
GO

--REGISTRAR PRODUCTOS
CREATE OR ALTER PROCEDURE CATALOGO.REGISTRAR_PRODUCTO(@CATEGORIA VARCHAR(30), 
@NOMBRE VARCHAR(30),@PRECIO NUMERIC(10,2), @PRECIO_REFERENCIA NUMERIC(10,2), 
@UNIDAD_REFERENCIA VARCHAR(5), @FECHA DATE) AS
BEGIN
	INSERT INTO CATALOGO.PRODUCTO(CATEGORIA, NOMBRE, PRECIO, PRECIO_REFERENCIA, 
	UNIDAD_REFERENCIA, FECHA) 
	VALUES (@CATEGORIA, @NOMBRE, @PRECIO, @PRECIO_REFERENCIA, @UNIDAD_REFERENCIA, @FECHA)
END
GO

-- BAJA DE PRODUCTOS
CREATE OR ALTER PROCEDURE CATALOGO.ELIMINAR_PRODUCTO(@ID INT) AS
BEGIN
	DELETE FROM CATALOGO.PRODUCTO WHERE ID = @ID
END
GO

--REGISTRO DE ACCESORIOS ELECTRONICOS
CREATE OR ALTER PROCEDURE CATALOGO.REGISTRAR_ACCESORIOS_ELECTRONICOS(@PRODUCTO VARCHAR(20), 
@PRECIO_UNIT_USD NUMERIC(10, 2)) AS 
BEGIN
	INSERT INTO CATALOGO.ACCESORIO_ELECTRONICO VALUES (@PRODUCTO, @PRECIO_UNIT_USD)
END
GO

--BAJA DE ACCESORIOS ELECTRONICOS
CREATE OR ALTER PROCEDURE CATALOGO.ELIMINAR_ACCESORIOS_ELECTRONICOS(@ID INT) AS 
BEGIN
	DELETE FROM CATALOGO.ACCESORIO_ELECTRONICO WHERE ID = @ID
END
GO

--REGISTRAR PRODUCTO IMPORTADO
CREATE OR ALTER PROCEDURE CATALOGO.REGISTRAR_PRODUCTO_IMPORTADO(@NOMBRE VARCHAR(20), 
@PROVEEDOR VARCHAR(20), @CATEGORIA VARCHAR(20), @CANT_POR_UNIDAD INT,  
@PRECIO_UNIDAD NUMERIC(10, 2)) AS 
BEGIN
	INSERT INTO CATALOGO.PRODUCTO_IMPORTADO(NombreProducto, 
	proveedor, categoria, CantidadPorUnidad, PrecioUnidad) 
	VALUES (@NOMBRE, @PROVEEDOR, @CATEGORIA, @CANT_POR_UNIDAD, @PRECIO_UNIDAD)
END
GO

--BAJA PRODUCTO IMPORTADO
CREATE OR ALTER PROCEDURE CATALOGO.BAJA_PRODUCTO_IMPORTADO(@ID INT) AS 
BEGIN
	DELETE FROM CATALOGO.PRODUCTO_IMPORTADO WHERE IDPRODUCTO = @ID
END
GO

-- MODIFICAR NOMBRE PRODUCTO IMPORTADO
CREATE OR ALTER PROCEDURE CATALOGO.ACTUALIZAR_NOMBRE_PRODUCTO_IMPORTADO(@ID INT, 
@NOMBRE VARCHAR(20)) AS 
BEGIN
	UPDATE CATALOGO.producto_importado SET NOMBREPRODUCTO = @NOMBRE WHERE IDPRODUCTO = @ID
END
GO

-- MODIFICAR PROVEEDOR PRODUCTO IMPORTADO
CREATE OR ALTER PROCEDURE CATALOGO.ACTUALIZAR_PROVEEDOR_PRODUCTO_IMPORTADO(@ID INT, 
@PROVEEDOR VARCHAR(20)) AS 
BEGIN
	UPDATE CATALOGO.producto_importado SET PROVEEDOR = @PROVEEDOR WHERE IDPRODUCTO = @ID
END
GO

-- MODIFICAR CATEGORIA PRODUCTO IMPORTADO
CREATE OR ALTER PROCEDURE CATALOGO.ACTUALIZAR_CATEGORIA_PRODUCTO_IMPORTADO(@ID INT, 
@CATEGORIA VARCHAR(20)) AS 
BEGIN
	UPDATE CATALOGO.producto_importado SET CATEGORIA = @CATEGORIA WHERE IDPRODUCTO = @ID
END
GO

-- MODIFICAR CANTIDAD POR UNIDAD PRODUCTO IMPORTADO
CREATE OR ALTER PROCEDURE CATALOGO.ACTUALIZAR_CANT_POR_UNIDAD_PRODUCTO_IMPORTADO(@ID INT, 
@CANT INT) AS 
BEGIN
	UPDATE CATALOGO.producto_importado SET CANTIDADPORUNIDAD = @CANT WHERE IDPRODUCTO = @ID
END
GO

-- MODIFICAR PRECIO POR UNIDAD PRODUCTO IMPORTADO
CREATE OR ALTER PROCEDURE CATALOGO.ACTUALIZAR_PRECIO_PRODUCTO_IMPORTADO(@ID INT, 
@PRECIO NUMERIC(10, 2)) AS 
BEGIN
	UPDATE CATALOGO.producto_importado SET PRECIOUNIDAD = @PRECIO WHERE IDPRODUCTO = @ID
END
GO

-- MODIFICAR PRODUCTO ACCESORIOS ELECTRONICOS
CREATE OR ALTER PROCEDURE CATALOGO.ACTUALIZAR_PRODUCTO_ACCESORIOS_ELECTRONICOS(@ID INT, 
@PRODUCTO VARCHAR(20)) AS 
BEGIN
	UPDATE CATALOGO.accesorio_electronico SET PRODUCTO = @PRODUCTO WHERE ID = @ID
END
GO

-- MODIFICAR PRECIO ACCESORIOS ELECTRONICOS
CREATE OR ALTER PROCEDURE CATALOGO.ACTUALIZAR_PRECIO_ACCESORIOS_ELECTRONICOS(@ID INT, 
@PRECIO NUMERIC(10, 2)) AS 
BEGIN
	UPDATE CATALOGO.accesorio_electronico SET PRECIOUNITUSD = @PRECIO WHERE ID = @ID
END
GO

--MODIFICAR CATEGORICA PRODUCTO
CREATE OR ALTER PROCEDURE CATALOGO.ACTUALIZAR_CATEGORIA_PRODUCTO(@ID INT, @CAT VARCHAR(30))
AS 
BEGIN
	UPDATE CATALOGO.PRODUCTO SET CATEGORIA = @CAT WHERE ID = @ID
END
GO

--MODIFICAR CATEGORICA PRODUCTO
CREATE OR ALTER PROCEDURE CATALOGO.ACTUALIZAR_NOMBRE_PRODUCTO(@ID INT, @NOMBRE VARCHAR(30))
AS 
BEGIN
	UPDATE CATALOGO.PRODUCTO SET NOMBRE = @NOMBRE WHERE ID = @ID
END
GO

--MODIFICAR CATEGORIA PRODUCTO
CREATE OR ALTER PROCEDURE CATALOGO.ACTUALIZAR_PRECIO_REFERENCIA_PRODUCTO(@ID INT, 
@PRECIOREF NUMERIC(10,2)) AS 
BEGIN
	UPDATE CATALOGO.PRODUCTO SET PRECIO_REFERENCIA = @PRECIOREF WHERE ID = @ID
END
GO

--MODIFICAR PRECIO PRODUCTO
CREATE OR ALTER PROCEDURE CATALOGO.ACTUALIZAR_PRECIO_PRODUCTO(@ID INT, @PRECIO NUMERIC(10, 2))
AS 
BEGIN
	UPDATE CATALOGO.PRODUCTO SET PRECIO = @PRECIO WHERE ID = @ID
END
GO

--MODIFICAR UNIDAD DE REFERENCIA PRODUCTO
CREATE OR ALTER PROCEDURE CATALOGO.ACTUALIZAR_UNIDAD_REFERENCIA_PRODUCTO(@ID INT, @UNIDAD VARCHAR(5))
AS 
BEGIN
	UPDATE CATALOGO.PRODUCTO SET UNIDAD_REFERENCIA = @UNIDAD WHERE ID = @ID
END
GO

--MODIFICAR FECHA PRODUCTO
CREATE OR ALTER PROCEDURE CATALOGO.ACTUALIZAR_FECHA_PRODUCTO(@ID INT, @FECHA DATE) 
AS
BEGIN
	UPDATE CATALOGO.PRODUCTO SET FECHA = @FECHA WHERE ID = @ID
END
GO

--MODIFICAR DIRECCION SUCURSAL
CREATE OR ALTER PROCEDURE SUCURSAL.ACTUALIZAR_DIRECCION_SUCURSAL(@ID INT, @DIRECCION VARCHAR(70))
AS 
BEGIN
	UPDATE SUCURSAL.SUCURSAL SET DIRECCION = @DIRECCION WHERE ID = @ID
END
GO

--MODIFICAR HORARIO SUCURSAL
CREATE OR ALTER PROCEDURE SUCURSAL.ACTUALIZAR_HORARIO_SUCURSAL(@ID INT, @HORARIO VARCHAR(30))
AS 
BEGIN
	UPDATE SUCURSAL.SUCURSAL SET HORARIO = @HORARIO WHERE ID = @ID
END
GO

--MODIFICAR DIRECCION SUCURSAL
CREATE OR ALTER PROCEDURE SUCURSAL.ACTUALIZAR_TELEFONO_SUCURSAL(@ID INT, @TELEFONO VARCHAR(70))
AS 
BEGIN
	UPDATE SUCURSAL.SUCURSAL SET DIRECCION = @TELEFONO WHERE ID = @ID
END
GO

--INVALIDAR VENTA
CREATE OR ALTER PROCEDURE VENTASSUCURSAL.INVALIDAR_VENTA(@ID INT)
AS 
BEGIN
	UPDATE VENTASSUCURSAL.VENTA_REGISTRADA SET BAJA = NULL WHERE ID_FACTURA = @ID
END
GO

--VALIDAR VENTA
CREATE OR ALTER PROCEDURE VENTASSUCURSAL.VALIDAR_VENTA(@ID INT)
AS 
BEGIN
	UPDATE VENTASSUCURSAL.VENTA_REGISTRADA SET BAJA = GETDATE() WHERE ID_FACTURA = @ID
END
GO
--INSERTAR VENTA
CREATE OR ALTER PROCEDURE VENTASSUCURSAL.REGISTRAR_VENTA (@)

--INSERTAR FACTURA
CREATE OR ALTER PROCEDURE VENTASSUCURSAL.CREAR_FACTURA(@fecha date, @estado varchar(20), @cliente int, @detalle varchar(120), @id_factura varchar(12))
AS
BEGIN
	INSERT INTO ventasSucursal.factura(cliente_id, fecha, estado, detalle, id_factura)
	VALUES(@cliente, @fecha, @estado, @detalle, @id_factura);
END
GO
--CREAR NOTA DE CREDITO

CREATE OR ALTER PROCEDURE VENTASSUCURSAL.CREAR_NOTA(@CANTIDAD INT, @FECHA DATE, 
@FACTURAID VARCHAR(11), @PRODUCTOID INT)
AS
BEGIN
	INSERT INTO VENTASSUCURSAL.NOTA_CREDITO (cantidad, fecha, factura_id, producto_id) 
	VALUES (@CANTIDAD, @FECHA, @FACTURAID, @PRODUCTOID);
END