USE Com5600G04;
DELETE FROM SUCURSAL.SUCURSAL;
DELETE FROM SUCURSAL.EMPLEADO;
select * from sucursal.sucursal;
SELECT * FROM SUCURSAL.EMPLEADO;
SELECT * FROM ventasSucursal.CLIENTE;
SELECT * FROM CATALOGO.PRODUCTO;
SELECT * FROM VENTASSUCURSAL.FACTURA;
SELECT * FROM VENTASSUCURSAL.DETALLE;
SELECT * FROM VENTASSUCURSAL.venta_registrada;

--INTENTAMOS REGISTRAR UN EMPLEADO EN UNA SUCURSAL QUE NO EXISTE, DA ERROR Y NO LO REGISTRA

EXEC SUCURSAL.REGISTRAR_EMPLEADO 'José', 'Gonzales', 34527890, 'Presidente Perón 1438', 'josegonzales@gmail.com', 'josegon890@aurora.com', '20345278901', 'Encargado',
'San Justo', 'Noche 20-04';

--REGISTRAMOS UNA SUCURSAL EN SAN JUSTO

EXEC SUCURSAL.REGISTRAR_SUCURSAL 'San Justo', 'Perú 1903', 'Lunes a Viernes 12 a 19', '1551200406';

--AHORA SÍ PODEMOS REGISTRAR AL EMPLEADO PORQUE LA SUCURSAL EXISTE

EXEC SUCURSAL.REGISTRAR_EMPLEADO 'José', 'Gonzales', 34527890, 'Presidente Perón 1438', 'josegonzales@gmail.com', 'josegon890@aurora.com', '20345278901', 'Encargado',
'San Justo', 'Noche 20-04';

--DAMOS DE BAJA LA SUCURSAL Y AL DARLA DE BAJA Y LOS EMPLEADOS TAMBIÉN QUEDAN DESAFECTADOS

DECLARE @ID INT = (SELECT CAST(ID AS INT) FROM SUCURSAL.SUCURSAL WHERE CIUDAD LIKE 'San Justo');

EXEC SUCURSAL.BAJAR_SUCURSAL @ID;

--DAMOS DE ALTA LA SUCURSAL Y AL EMPLEADO
--NO PODEMOS DARLO DE ALTA SI LA SUCURSAL SIGUE DADA DE BAJA
EXEC SUCURSAL.ALTA_EMPLEADO 1;

--PRIMERO DAMOS DE ALTA LA SUCURSAL
EXEC SUCURSAL.ALTA_SUCURSAL 1
-- Y PODEMOS DAR DE ALTA AL EMPLEADO TAMBIÉN
EXEC SUCURSAL.ALTA_EMPLEADO 1

--REGISTRAMOS UN CLIENTE
EXEC VENTASSUCURSAL.REGISTRAR_CLIENTE 46700923, 'Normal' 

--INTENTAMOS CREAR UN NUEVO CLIENTE CON DIFERENTE TIPO PERO MISMO DNI
EXEC VENTASSUCURSAL.REGISTRAR_CLIENTE 46700923, 'Miembro', 'M'
--SOLO LO MODIFICA, NO REGISTRA UN DUPLICADO

--REGISTRAMOS 2 PRODUCTOS
EXEC CATALOGO.REGISTRAR_PRODUCTO 'Producto de belleza', 'Labial AVON', 120.43, 100, '10 cajas de 10 labiales', 'grms', '2024-11-27', 'AVON Argentina SA'
EXEC CATALOGO.REGISTRAR_PRODUCTO 'Limpieza', 'Trapo de piso', 76.99, 80, '50 Existencias', NULL, '2023-12-4', 'Trapos buenos SRL'

--RESGISTRO DE VENTA
--A LA HORA DE REGISTRAR UNA VENTA, EN PRIMER LUGAR SE GENERA LA PREFACTURA, ES DECIR, UNA FACTURA CON DATOS INICIALES, PERO INCOMPLETA

EXEC VENTASSUCURSAL.CREAR_PREFACTURA '2024-09-11', 'Pendiente', 1, 'B', '654-89-0924' --EL CÓDIGO SE RECIBE DEL SISTEMA DE FACTURACIÓN YA QUE LA GENERACIÓN DE FACTURAS ESTÁ FUERA DE ALCANCE

--AHORA SE CREAN LOS DETALLES DE LA VENTA
EXEC VENTASSUCURSAL.CREAR_DETALLE 2, 1, '654-89-0924'
EXEC VENTASSUCURSAL.CREAR_DETALLE 3, 2, '654-89-0924'

--LUEGO SE TERMINA DE EMITIR LA FACTURA
EXEC VENTASSUCURSAL.EMITIR_FACT '654-89-0924'

--LUEGO SE REGISTRA LA VENTA
EXEC VENTASSUCURSAL.REGISTRAR_VENTA 'San Justo', '2024-11-10', '14:00:00', 1, '654-89-0924', 'Cash' --DA ERROR PORQUE NO EXISTE ESE MEDIO DE PAGO
EXEC VENTASSUCURSAL.CREAR_MEDIO 'Cash'
EXEC VENTASSUCURSAL.REGISTRAR_VENTA 'San Justo', '2024-11-10', '14:00:00', 1, '654-89-0924', 'Cash'

--REGISTRAMOS EL PAGO EN LA FACTURA
EXEC VENTASSUCURSAL.ACTUALIZAR_PAGO_FACT '654-89-0924', 'Pagado'

--DAMOS DE BAJA LA VENTA, LO QUE A SU VEZ VA A DAR DE BAJA LA FACTURA
EXEC VENTASSUCURSAL.INVALIDAR_VENTA 2
--VEMOS QUE NO PODEMOS REALIZAR NADA CON UNA VENTA DADA DE BAJA
EXEC VENTASSUCURSAL.REGISTRAR_VENTA 'San Justo', '2024-11-10', '14:00:00', 1, '654-89-0924', 'Cash' 