use Com5600G04
--INTENTAMOS CREAR LA NOTA DE CRÉDITO
--SIENDO CAJERO:
EXECUTE AS LOGIN = 'cajero_sucursal'
EXEC credito.CREAR_NOTA '654-89-0924'
EXEC credito.ACTUALIZAR_PAGO_FACT '654-89-0924', 'Pagado'
EXEC credito.CREAR_NOTA '654-89-0924'
--CREAMOS LOS DETALLES (UNO POR CADA PRODUCTO DE LA NOTA DE CRÉDITO)

DECLARE @ID_PROD INT = (SELECT ID FROM CATALOGO.PRODUCTO WHERE NOMBRE = 'Labial AVON')
EXEC CATALOGO.ACTUALIZAR_PRECIO_PRODUCTO @ID_PROD, 100 --CAMBIAMOS EL PRECIO, PERO EL PRECIO DE LA NOTA DE CRÉDITO DEBE SER EL DEL DETALLE DE LA FACTURA

DECLARE @ID_FACT INT = (SELECT ID FROM VENTASSUCURSAL.FACTURA WHERE ID_FACTURA = '654-89-0924')
DECLARE @ID_NOTA INT = (SELECT ID FROM credito.NOTA_DE_CREDITO WHERE FACTURA_ID = @ID_FACT)
EXEC credito.CREAR_DETALLE_NOTA @ID_NOTA, 'Labial AVON', 3, @ID_FACT --NO PODEMOS CREARLA PORQUE EL DETALLE DE LA FACTURA DICE 2 PRODUCTOS Y ESTAMOS HACIENDO LA NOTA PARA 3, AL CAMBIARLO FUNCIONA

EXEC credito.CREAR_DETALLE_NOTA @ID_NOTA, 'Labial AVON', 2, @ID_FACT --FUNCIONA CORRECTAMENTE

EXEC credito.EMITIR_NOTA @ID_NOTA